name: Upload Beta Version

on:
  release:
    types: [created]

jobs:
  deploy:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Change package name to beta
      uses: jacobtomlinson/gha-find-replace@0.1.3
      with:
        include: "pyproject.toml"
        find: "snek-scripts"
        replace: "snek-scripts-beta"
    - name: Build and publish to PyPI
      uses: JRubics/poetry-publish@v1.6
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
    - name: Undo package name change
      uses: jacobtomlinson/gha-find-replace@0.1.3
      with:
        include: "pyproject.toml"
        find: "snek-scripts-beta"
        replace: "snek-scripts"